// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PythonExam.Models
{
    public partial class LightStatusHistory
    {
        public long LightStatusHistory1 { get; set; }
        public long? LightId { get; set; }
        public DateTime? LightStatusTime { get; set; }
    }
}