// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PythonExam.Models
{
    public partial class pybeeContext : DbContext
    {
        public pybeeContext()
        {
        }

        public pybeeContext(DbContextOptions<pybeeContext> options)
            : base(options)
        {
        }

        public virtual DbSet<LightStatusHistory> LightStatusHistories { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<TypeOfHome> TypeOfHomes { get; set; }
        public virtual DbSet<TypeOfLight> TypeOfLights { get; set; }
        public virtual DbSet<TypeOfRoom> TypeOfRooms { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LightStatusHistory>(entity =>
            {
                entity.HasKey(e => e.LightStatusHistory1)
                    .HasName("PK__LightSta__270BC32B37681953");

                entity.ToTable("LightStatusHistory");

                entity.Property(e => e.LightStatusHistory1).HasColumnName("LightStatusHistory");

                entity.Property(e => e.LightId).HasColumnName("LightID");

                entity.Property(e => e.LightStatusTime).HasColumnType("datetime");
            });

            modelBuilder.Entity<Login>(entity =>
            {
                entity.HasKey(e => e.UserId)
                    .HasName("PK__Login__1788CCACD957EE91");

                entity.ToTable("Login");

                entity.Property(e => e.UserId).HasColumnName("UserID");

                entity.Property(e => e.HomeId).HasColumnName("HomeID");

                entity.Property(e => e.UserName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.UserPassword)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<TypeOfHome>(entity =>
            {
                entity.HasKey(e => e.HomeId)
                    .HasName("PK__TypeOfHo__105D642269554272");

                entity.ToTable("TypeOfHome");

                entity.Property(e => e.HomeId).HasColumnName("HomeID");

                entity.Property(e => e.HomeName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.RoomId).HasColumnName("RoomID");
            });

            modelBuilder.Entity<TypeOfLight>(entity =>
            {
                entity.HasKey(e => e.LightId)
                    .HasName("PK__TypeOfLi__C2FB829FD686A8F7");

                entity.ToTable("TypeOfLight");

                entity.Property(e => e.LightId).HasColumnName("LightID");

                entity.Property(e => e.LightColor)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.LightName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<TypeOfRoom>(entity =>
            {
                entity.HasKey(e => e.RoomId)
                    .HasName("PK__TypeOfRo__32863919A187CAD3");

                entity.ToTable("TypeOfRoom");

                entity.Property(e => e.RoomId).HasColumnName("RoomID");

                entity.Property(e => e.LightId).HasColumnName("LightID");

                entity.Property(e => e.RoomName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}