// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PythonExam.Models
{
    public partial class TypeOfLight
    {
        public long LightId { get; set; }
        public string LightName { get; set; }
        public string LightColor { get; set; }
        public int? LightBightness { get; set; }
        public int? LightStatus { get; set; }
    }
}