// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PythonExam.Models
{
    public partial class TypeOfHome
    {
        public long HomeId { get; set; }
        public string HomeName { get; set; }
        public long? RoomId { get; set; }
    }
}