// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PythonExam.Models
{
    public partial class TypeOfRoom
    {
        public long RoomId { get; set; }
        public string RoomName { get; set; }
        public long? LightId { get; set; }
    }
}